# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(951, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(951, 730))
        MainWindow.setMaximumSize(QtCore.QSize(951, 730))
        MainWindow.setSizeIncrement(QtCore.QSize(951, 730))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #263238;")
        MainWindow.setAnimated(False)
        self.frm_root = QtWidgets.QWidget(MainWindow)
        self.frm_root.setObjectName("frm_root")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_root)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frm_container = QtWidgets.QFrame(self.frm_root)
        self.frm_container.setMinimumSize(QtCore.QSize(951, 730))
        self.frm_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_container.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_container.setLineWidth(0)
        self.frm_container.setObjectName("frm_container")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.frm_container)
        self.vboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.frm_header = QtWidgets.QFrame(self.frm_container)
        self.frm_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_header.setLineWidth(0)
        self.frm_header.setObjectName("frm_header")
        self.label = QtWidgets.QLabel(self.frm_header)
        self.label.setGeometry(QtCore.QRect(80, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white;")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frm_header)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lbl_username = QtWidgets.QLabel(self.frm_header)
        self.lbl_username.setGeometry(QtCore.QRect(90, 40, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_username.setFont(font)
        self.lbl_username.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_username.setObjectName("lbl_username")
        self.btn_logout = QtWidgets.QPushButton(self.frm_header)
        self.btn_logout.setGeometry(QtCore.QRect(900, 20, 41, 31))
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout.setIcon(icon)
        self.btn_logout.setIconSize(QtCore.QSize(30, 30))
        self.btn_logout.setFlat(True)
        self.btn_logout.setObjectName("btn_logout")
        self.vboxlayout.addWidget(self.frm_header)
        self.frm_body = QtWidgets.QFrame(self.frm_container)
        self.frm_body.setMinimumSize(QtCore.QSize(0, 100))
        self.frm_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_body.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_body.setLineWidth(0)
        self.frm_body.setObjectName("frm_body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frm_barra = QtWidgets.QFrame(self.frm_body)
        self.frm_barra.setMinimumSize(QtCore.QSize(50, 1))
        self.frm_barra.setStyleSheet("")
        self.frm_barra.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_barra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_barra.setLineWidth(0)
        self.frm_barra.setObjectName("frm_barra")
        self.btn_tratamientos = QtWidgets.QPushButton(self.frm_barra)
        self.btn_tratamientos.setGeometry(QtCore.QRect(-10, 290, 180, 41))
        self.btn_tratamientos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tratamientos.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_tratamientos.setObjectName("btn_tratamientos")
        self.btn_proveedores = QtWidgets.QPushButton(self.frm_barra)
        self.btn_proveedores.setGeometry(QtCore.QRect(-10, 340, 180, 41))
        self.btn_proveedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_proveedores.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_proveedores.setObjectName("btn_proveedores")
        self.btn_usuarios = QtWidgets.QPushButton(self.frm_barra)
        self.btn_usuarios.setGeometry(QtCore.QRect(-10, 90, 180, 41))
        self.btn_usuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_usuarios.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_usuarios.setObjectName("btn_usuarios")
        self.btn_personal = QtWidgets.QPushButton(self.frm_barra)
        self.btn_personal.setGeometry(QtCore.QRect(-10, 190, 180, 41))
        self.btn_personal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_personal.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_personal.setObjectName("btn_personal")
        self.btn_personas = QtWidgets.QPushButton(self.frm_barra)
        self.btn_personas.setGeometry(QtCore.QRect(-10, 40, 180, 41))
        self.btn_personas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_personas.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_personas.setObjectName("btn_personas")
        self.btn_pacientes = QtWidgets.QPushButton(self.frm_barra)
        self.btn_pacientes.setGeometry(QtCore.QRect(-10, 240, 180, 41))
        self.btn_pacientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pacientes.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_pacientes.setObjectName("btn_pacientes")
        self.btn_horarios = QtWidgets.QPushButton(self.frm_barra)
        self.btn_horarios.setGeometry(QtCore.QRect(-10, 140, 180, 41))
        self.btn_horarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_horarios.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_horarios.setObjectName("btn_horarios")
        self.btn_productos = QtWidgets.QPushButton(self.frm_barra)
        self.btn_productos.setGeometry(QtCore.QRect(-10, 390, 180, 41))
        self.btn_productos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_productos.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_productos.setObjectName("btn_productos")
        self.horizontalLayout_2.addWidget(self.frm_barra)
        self.frm_main = QtWidgets.QFrame(self.frm_body)
        self.frm_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frm_main.setAutoFillBackground(False)
        self.frm_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_main.setLineWidth(1)
        self.frm_main.setObjectName("frm_main")
        self.label_3 = QtWidgets.QLabel(self.frm_main)
        self.label_3.setGeometry(QtCore.QRect(210, 130, 231, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/empty.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.frm_main)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.vboxlayout.addWidget(self.frm_body)
        self.vboxlayout.setStretch(0, 1)
        self.vboxlayout.setStretch(1, 9)
        self.horizontalLayout.addWidget(self.frm_container)
        MainWindow.setCentralWidget(self.frm_root)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strong Teeth"))
        self.label.setText(_translate("MainWindow", "Strong Teeth"))
        self.lbl_username.setText(_translate("MainWindow", "N/A"))
        self.btn_tratamientos.setText(_translate("MainWindow", "Tratamientos"))
        self.btn_proveedores.setText(_translate("MainWindow", "Proveedores"))
        self.btn_usuarios.setText(_translate("MainWindow", "Usuarios"))
        self.btn_personal.setText(_translate("MainWindow", "Personal"))
        self.btn_personas.setText(_translate("MainWindow", "Personas"))
        self.btn_pacientes.setText(_translate("MainWindow", "Pacientes"))
        self.btn_horarios.setText(_translate("MainWindow", "Horarios"))
        self.btn_productos.setText(_translate("MainWindow", "Productos"))
