# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(964, 724)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #263238;")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white;")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 521, 531))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/logo.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(670, 110, 191, 41))
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.btn_save_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_2.setGeometry(QtCore.QRect(670, 170, 191, 41))
        self.btn_save_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_2.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_2.setObjectName("btn_save_2")
        self.btn_save_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_3.setGeometry(QtCore.QRect(670, 230, 191, 41))
        self.btn_save_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_3.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_3.setObjectName("btn_save_3")
        self.btn_save_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_4.setGeometry(QtCore.QRect(670, 350, 191, 41))
        self.btn_save_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_4.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_4.setObjectName("btn_save_4")
        self.btn_save_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_5.setGeometry(QtCore.QRect(670, 290, 191, 41))
        self.btn_save_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_5.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_5.setObjectName("btn_save_5")
        self.btn_save_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_6.setGeometry(QtCore.QRect(670, 410, 191, 41))
        self.btn_save_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_6.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_6.setObjectName("btn_save_6")
        self.btn_save_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_7.setGeometry(QtCore.QRect(670, 470, 191, 41))
        self.btn_save_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_7.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_7.setObjectName("btn_save_7")
        self.btn_save_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_8.setGeometry(QtCore.QRect(670, 530, 191, 41))
        self.btn_save_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_8.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.975124, y2:1, stop:0 rgba(170, 4, 176, 255), stop:1 rgba(69, 137, 158, 255));\n"
"}")
        self.btn_save_8.setObjectName("btn_save_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 680, 67, 17))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lbl_username = QtWidgets.QLabel(self.centralwidget)
        self.lbl_username.setGeometry(QtCore.QRect(80, 680, 241, 17))
        self.lbl_username.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_username.setObjectName("lbl_username")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(910, 670, 41, 31))
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout.setIcon(icon)
        self.btn_logout.setIconSize(QtCore.QSize(30, 30))
        self.btn_logout.setFlat(True)
        self.btn_logout.setObjectName("btn_logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strong Teeth"))
        self.label.setText(_translate("MainWindow", "Strong Teeth"))
        self.btn_save.setText(_translate("MainWindow", "Personas"))
        self.btn_save_2.setText(_translate("MainWindow", "Usuarios"))
        self.btn_save_3.setText(_translate("MainWindow", "Horarios"))
        self.btn_save_4.setText(_translate("MainWindow", "Pacientes"))
        self.btn_save_5.setText(_translate("MainWindow", "Personal"))
        self.btn_save_6.setText(_translate("MainWindow", "Tratamientos"))
        self.btn_save_7.setText(_translate("MainWindow", "Proveedores"))
        self.btn_save_8.setText(_translate("MainWindow", "Productos"))
        self.label_3.setText(_translate("MainWindow", "Usuario:"))
        self.lbl_username.setText(_translate("MainWindow", "N/A"))
