# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(300, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 420))
        MainWindow.setMaximumSize(QtCore.QSize(300, 420))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #263238;")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 81, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/home/hans/Documentos/eva/dental/ui/../assets/images/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white;")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(20, -1, 20, 40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_username = QtWidgets.QLineEdit(self.frame_4)
        self.input_username.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.input_username.setObjectName("input_username")
        self.verticalLayout_3.addWidget(self.input_username)
        self.input_password = QtWidgets.QLineEdit(self.frame_4)
        self.input_password.setEnabled(True)
        self.input_password.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.input_password.setInputMask("")
        self.input_password.setMaxLength(24)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.input_password.setClearButtonEnabled(True)
        self.input_password.setObjectName("input_password")
        self.verticalLayout_3.addWidget(self.input_password)
        self.btn_save = QtWidgets.QPushButton(self.frame_4)
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    background-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_3.addWidget(self.btn_save)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.input_username.setPlaceholderText(_translate("MainWindow", "Correo Electrónico"))
        self.input_password.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.btn_save.setText(_translate("MainWindow", "Entrar"))
