# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/login copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(291, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: #263238;")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_username = QtWidgets.QLineEdit(self.centralwidget)
        self.input_username.setGeometry(QtCore.QRect(50, 90, 191, 41))
        self.input_username.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.input_username.setObjectName("input_username")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white;")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setEnabled(True)
        self.input_password.setGeometry(QtCore.QRect(50, 150, 191, 41))
        self.input_password.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.input_password.setInputMask("")
        self.input_password.setMaxLength(24)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.input_password.setClearButtonEnabled(True)
        self.input_password.setObjectName("input_password")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(50, 220, 191, 41))
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    background-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.input_username.setPlaceholderText(_translate("MainWindow", "Correo Electrónico"))
        self.label.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.input_password.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.btn_save.setText(_translate("MainWindow", "Entrar"))
