# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/marca.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_persona(object):
    def setupUi(self, w_persona):
        w_persona.setObjectName("w_persona")
        w_persona.setWindowModality(QtCore.Qt.WindowModal)
        w_persona.setEnabled(True)
        w_persona.resize(380, 522)
        w_persona.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(w_persona)
        self.centralwidget.setObjectName("centralwidget")
        self.persona_tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.persona_tabla.setGeometry(QtCore.QRect(30, 200, 311, 271))
        self.persona_tabla.setObjectName("persona_tabla")
        self.persona_tabla.setColumnCount(3)
        self.persona_tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.persona_tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.persona_tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.persona_tabla.setHorizontalHeaderItem(2, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 30, 89, 25))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 181, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 181, 17))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 70, 181, 17))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 90, 301, 91))
        self.textEdit.setObjectName("textEdit")
        w_persona.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(w_persona)
        self.statusbar.setObjectName("statusbar")
        w_persona.setStatusBar(self.statusbar)

        self.retranslateUi(w_persona)
        QtCore.QMetaObject.connectSlotsByName(w_persona)

    def retranslateUi(self, w_persona):
        _translate = QtCore.QCoreApplication.translate
        w_persona.setWindowTitle(_translate("w_persona", "Marcas"))
        item = self.persona_tabla.horizontalHeaderItem(0)
        item.setText(_translate("w_persona", "#ID"))
        item = self.persona_tabla.horizontalHeaderItem(1)
        item.setText(_translate("w_persona", "Nombre"))
        item = self.persona_tabla.horizontalHeaderItem(2)
        item.setText(_translate("w_persona", "Descripción"))
        self.pushButton.setText(_translate("w_persona", "Guardar"))
        self.label.setText(_translate("w_persona", "Nombre"))
        self.label_5.setText(_translate("w_persona", "Dirección"))
