# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hans/Documentos/eva/dental/ui/persona_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 630)
        Dialog.setMinimumSize(QtCore.QSize(400, 630))
        Dialog.setMaximumSize(QtCore.QSize(400, 630))
        Dialog.setStyleSheet("background-color: #263238;")
        Dialog.setModal(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_title.setStyleSheet("color: white;")
        self.lbl_title.setLineWidth(1)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_nombres = QtWidgets.QLineEdit(self.frame_2)
        self.input_nombres.setStyleSheet("")
        self.input_nombres.setObjectName("input_nombres")
        self.verticalLayout_3.addWidget(self.input_nombres)
        self.input_apellido_paterno = QtWidgets.QLineEdit(self.frame_2)
        self.input_apellido_paterno.setStyleSheet("QLineEdit {\n"
"    color:  white;\n"
"    border-style:  solid;\n"
"    border-width: 1.5px;\n"
"    border-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.input_apellido_paterno.setObjectName("input_apellido_paterno")
        self.verticalLayout_3.addWidget(self.input_apellido_paterno)
        self.input_apellido_materno = QtWidgets.QLineEdit(self.frame_2)
        self.input_apellido_materno.setObjectName("input_apellido_materno")
        self.verticalLayout_3.addWidget(self.input_apellido_materno)
        self.input_numero_identidad = QtWidgets.QLineEdit(self.frame_2)
        self.input_numero_identidad.setObjectName("input_numero_identidad")
        self.verticalLayout_3.addWidget(self.input_numero_identidad)
        self.date_fecha_nacimiento = QtWidgets.QDateEdit(self.frame_2)
        self.date_fecha_nacimiento.setObjectName("date_fecha_nacimiento")
        self.verticalLayout_3.addWidget(self.date_fecha_nacimiento)
        self.cmb_genero = QtWidgets.QComboBox(self.frame_2)
        self.cmb_genero.setObjectName("cmb_genero")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.verticalLayout_3.addWidget(self.cmb_genero)
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton {\n"
"    color:  white;\n"
"    background-color: #0097a7;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_3.addWidget(self.btn_save)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 8)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Persona"))
        self.lbl_title.setText(_translate("Dialog", "Crear Persona"))
        self.input_nombres.setPlaceholderText(_translate("Dialog", "Nombre"))
        self.input_apellido_paterno.setPlaceholderText(_translate("Dialog", "Apellido Paterno"))
        self.input_apellido_materno.setPlaceholderText(_translate("Dialog", "Apellido Materno"))
        self.input_numero_identidad.setPlaceholderText(_translate("Dialog", "N° Identidad"))
        self.date_fecha_nacimiento.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.cmb_genero.setItemText(0, _translate("Dialog", "Masculino"))
        self.cmb_genero.setItemText(1, _translate("Dialog", "Femenino"))
        self.btn_save.setText(_translate("Dialog", "Guardar"))
